before_script:
  - apt-get update -qq && apt-get install -y -qq build-essential ncurses-dev libproc-processtable-perl fakeroot libelf-dev libssl-dev bison flex pigz bc

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: 
    - echo "Running tests"
    - make modules

build:
  stage: build
  script: 
    - echo "Building the app"
    - make deb-pkg
  when: manual

deploy:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: https://staging.example.com
  when: manual
  only:
  - master

